os: 'linux'
dist: 'bionic'

language: 'python'
python:
  - '3.7'
  - '3.8'

cache:
    pip: true

install:
  - 'pip install -r requirements.txt'

script:
  - 'coverage run -m unittest tests -vb'

after_success:
  - 'coverage report -m'
  - 'pip install codecov'
  - 'codecov'
