# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.grammarList = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grammarList.sizePolicy().hasHeightForWidth())
        self.grammarList.setSizePolicy(sizePolicy)
        self.grammarList.setMinimumSize(QtCore.QSize(100, 0))
        self.grammarList.setMaximumSize(QtCore.QSize(150, 16777215))
        self.grammarList.setObjectName("grammarList")
        self.horizontalLayout_2.addWidget(self.grammarList)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineInputGrammarName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineInputGrammarName.setText("")
        self.lineInputGrammarName.setObjectName("lineInputGrammarName")
        self.horizontalLayout.addWidget(self.lineInputGrammarName)
        self.buttonCreateGrammar = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCreateGrammar.setObjectName("buttonCreateGrammar")
        self.horizontalLayout.addWidget(self.buttonCreateGrammar)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.textEditGrammarInput = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditGrammarInput.setObjectName("textEditGrammarInput")
        self.verticalLayout_2.addWidget(self.textEditGrammarInput)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonNF = QtWidgets.QPushButton(self.centralwidget)
        self.buttonNF.setObjectName("buttonNF")
        self.verticalLayout.addWidget(self.buttonNF)
        self.buttonVI = QtWidgets.QPushButton(self.centralwidget)
        self.buttonVI.setObjectName("buttonVI")
        self.verticalLayout.addWidget(self.buttonVI)
        self.buttonNA = QtWidgets.QPushButton(self.centralwidget)
        self.buttonNA.setObjectName("buttonNA")
        self.verticalLayout.addWidget(self.buttonNA)
        self.buttonNE = QtWidgets.QPushButton(self.centralwidget)
        self.buttonNE.setObjectName("buttonNE")
        self.verticalLayout.addWidget(self.buttonNE)
        self.buttonToPropper = QtWidgets.QPushButton(self.centralwidget)
        self.buttonToPropper.setObjectName("buttonToPropper")
        self.verticalLayout.addWidget(self.buttonToPropper)
        self.buttonFirst = QtWidgets.QPushButton(self.centralwidget)
        self.buttonFirst.setObjectName("buttonFirst")
        self.verticalLayout.addWidget(self.buttonFirst)
        self.buttonFirstNT = QtWidgets.QPushButton(self.centralwidget)
        self.buttonFirstNT.setObjectName("buttonFirstNT")
        self.verticalLayout.addWidget(self.buttonFirstNT)
        self.buttonFollow = QtWidgets.QPushButton(self.centralwidget)
        self.buttonFollow.setObjectName("buttonFollow")
        self.verticalLayout.addWidget(self.buttonFollow)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEditFactorSteps = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditFactorSteps.setObjectName("lineEditFactorSteps")
        self.horizontalLayout_3.addWidget(self.lineEditFactorSteps)
        self.buttonFactorSteps = QtWidgets.QPushButton(self.centralwidget)
        self.buttonFactorSteps.setObjectName("buttonFactorSteps")
        self.horizontalLayout_3.addWidget(self.buttonFactorSteps)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.buttonCheckRecursion = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCheckRecursion.setObjectName("buttonCheckRecursion")
        self.verticalLayout.addWidget(self.buttonCheckRecursion)
        self.buttonRemoveDirectRec = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRemoveDirectRec.setObjectName("buttonRemoveDirectRec")
        self.verticalLayout.addWidget(self.buttonRemoveDirectRec)
        self.buttonRemoveIndirectRec = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRemoveIndirectRec.setObjectName("buttonRemoveIndirectRec")
        self.verticalLayout.addWidget(self.buttonRemoveIndirectRec)
        self.buttonFinite = QtWidgets.QPushButton(self.centralwidget)
        self.buttonFinite.setObjectName("buttonFinite")
        self.verticalLayout.addWidget(self.buttonFinite)
        self.buttonEmpty = QtWidgets.QPushButton(self.centralwidget)
        self.buttonEmpty.setObjectName("buttonEmpty")
        self.verticalLayout.addWidget(self.buttonEmpty)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.textEditConsole = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditConsole.sizePolicy().hasHeightForWidth())
        self.textEditConsole.setSizePolicy(sizePolicy)
        self.textEditConsole.setMinimumSize(QtCore.QSize(0, 150))
        self.textEditConsole.setAcceptRichText(False)
        self.textEditConsole.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEditConsole.setObjectName("textEditConsole")
        self.verticalLayout_3.addWidget(self.textEditConsole)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineInputGrammarName.setPlaceholderText(_translate("MainWindow", "Name..."))
        self.buttonCreateGrammar.setText(_translate("MainWindow", "Create"))
        self.textEditGrammarInput.setPlaceholderText(_translate("MainWindow", "S -> aS | a"))
        self.buttonNF.setText(_translate("MainWindow", "Nf"))
        self.buttonVI.setText(_translate("MainWindow", "Vi"))
        self.buttonNA.setText(_translate("MainWindow", "Na"))
        self.buttonNE.setText(_translate("MainWindow", "Ne"))
        self.buttonToPropper.setText(_translate("MainWindow", "To Proper"))
        self.buttonFirst.setText(_translate("MainWindow", "First"))
        self.buttonFirstNT.setText(_translate("MainWindow", "First NT"))
        self.buttonFollow.setText(_translate("MainWindow", "Follow"))
        self.lineEditFactorSteps.setPlaceholderText(_translate("MainWindow", "Factor steps"))
        self.buttonFactorSteps.setText(_translate("MainWindow", "Check Factor"))
        self.buttonCheckRecursion.setText(_translate("MainWindow", "Check Recursion"))
        self.buttonRemoveDirectRec.setText(_translate("MainWindow", "Remove Direct Recursion"))
        self.buttonRemoveIndirectRec.setText(_translate("MainWindow", "Remove Indirect Recursion"))
        self.buttonFinite.setText(_translate("MainWindow", "Finite"))
        self.buttonEmpty.setText(_translate("MainWindow", "Empty"))
        self.textEditConsole.setPlaceholderText(_translate("MainWindow", "Console"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

